/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebinarRouteImport } from './routes/webinar'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiPublicSumitWebhookRouteImport } from './routes/api/public/sumit-webhook'
import { Route as ApiPublicSumitReturnRouteImport } from './routes/api/public/sumit-return'
import { Route as ApiAdminVerifyTransactionRouteImport } from './routes/api/admin/verify-transaction'

const WebinarRoute = WebinarRouteImport.update({
  id: '/webinar',
  path: '/webinar',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSumitWebhookRoute = ApiPublicSumitWebhookRouteImport.update({
  id: '/api/public/sumit-webhook',
  path: '/api/public/sumit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSumitReturnRoute = ApiPublicSumitReturnRouteImport.update({
  id: '/api/public/sumit-return',
  path: '/api/public/sumit-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyTransactionRoute =
  ApiAdminVerifyTransactionRouteImport.update({
    id: '/api/admin/verify-transaction',
    path: '/api/admin/verify-transaction',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/webinar': typeof WebinarRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/verify-transaction': typeof ApiAdminVerifyTransactionRoute
  '/api/public/sumit-return': typeof ApiPublicSumitReturnRoute
  '/api/public/sumit-webhook': typeof ApiPublicSumitWebhookRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/webinar': typeof WebinarRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/verify-transaction': typeof ApiAdminVerifyTransactionRoute
  '/api/public/sumit-return': typeof ApiPublicSumitReturnRoute
  '/api/public/sumit-webhook': typeof ApiPublicSumitWebhookRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/webinar': typeof WebinarRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/verify-transaction': typeof ApiAdminVerifyTransactionRoute
  '/api/public/sumit-return': typeof ApiPublicSumitReturnRoute
  '/api/public/sumit-webhook': typeof ApiPublicSumitWebhookRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/thank-you'
    | '/webinar'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/schedule'
    | '/admin/settings'
    | '/payment/success'
    | '/admin/'
    | '/api/admin/verify-transaction'
    | '/api/public/sumit-return'
    | '/api/public/sumit-webhook'
    | '/api/public/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/thank-you'
    | '/webinar'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/schedule'
    | '/admin/settings'
    | '/payment/success'
    | '/admin'
    | '/api/admin/verify-transaction'
    | '/api/public/sumit-return'
    | '/api/public/sumit-webhook'
    | '/api/public/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/thank-you'
    | '/webinar'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/pricing'
    | '/admin/schedule'
    | '/admin/settings'
    | '/payment/success'
    | '/admin/'
    | '/api/admin/verify-transaction'
    | '/api/public/sumit-return'
    | '/api/public/sumit-webhook'
    | '/api/public/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThankYouRoute: typeof ThankYouRoute
  WebinarRoute: typeof WebinarRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminVerifyTransactionRoute: typeof ApiAdminVerifyTransactionRoute
  ApiPublicSumitReturnRoute: typeof ApiPublicSumitReturnRoute
  ApiPublicSumitWebhookRoute: typeof ApiPublicSumitWebhookRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webinar': {
      id: '/webinar'
      path: '/webinar'
      fullPath: '/webinar'
      preLoaderRoute: typeof WebinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sumit-webhook': {
      id: '/api/public/sumit-webhook'
      path: '/api/public/sumit-webhook'
      fullPath: '/api/public/sumit-webhook'
      preLoaderRoute: typeof ApiPublicSumitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sumit-return': {
      id: '/api/public/sumit-return'
      path: '/api/public/sumit-return'
      fullPath: '/api/public/sumit-return'
      preLoaderRoute: typeof ApiPublicSumitReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify-transaction': {
      id: '/api/admin/verify-transaction'
      path: '/api/admin/verify-transaction'
      fullPath: '/api/admin/verify-transaction'
      preLoaderRoute: typeof ApiAdminVerifyTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThankYouRoute: ThankYouRoute,
  WebinarRoute: WebinarRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminVerifyTransactionRoute: ApiAdminVerifyTransactionRoute,
  ApiPublicSumitReturnRoute: ApiPublicSumitReturnRoute,
  ApiPublicSumitWebhookRoute: ApiPublicSumitWebhookRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
