/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebinarRouteImport } from './routes/webinar'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as ApiPublicSumitWebhookRouteImport } from './routes/api/public/sumit-webhook'
import { Route as ApiPublicSumitReturnRouteImport } from './routes/api/public/sumit-return'

const WebinarRoute = WebinarRouteImport.update({
  id: '/webinar',
  path: '/webinar',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSumitWebhookRoute = ApiPublicSumitWebhookRouteImport.update({
  id: '/api/public/sumit-webhook',
  path: '/api/public/sumit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSumitReturnRoute = ApiPublicSumitReturnRouteImport.update({
  id: '/api/public/sumit-return',
  path: '/api/public/sumit-return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/webinar': typeof WebinarRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/public/sumit-return': typeof ApiPublicSumitReturnRoute
  '/api/public/sumit-webhook': typeof ApiPublicSumitWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/webinar': typeof WebinarRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/public/sumit-return': typeof ApiPublicSumitReturnRoute
  '/api/public/sumit-webhook': typeof ApiPublicSumitWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thank-you': typeof ThankYouRoute
  '/webinar': typeof WebinarRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/public/sumit-return': typeof ApiPublicSumitReturnRoute
  '/api/public/sumit-webhook': typeof ApiPublicSumitWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/thank-you'
    | '/webinar'
    | '/payment/success'
    | '/api/public/sumit-return'
    | '/api/public/sumit-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/thank-you'
    | '/webinar'
    | '/payment/success'
    | '/api/public/sumit-return'
    | '/api/public/sumit-webhook'
  id:
    | '__root__'
    | '/'
    | '/thank-you'
    | '/webinar'
    | '/payment/success'
    | '/api/public/sumit-return'
    | '/api/public/sumit-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThankYouRoute: typeof ThankYouRoute
  WebinarRoute: typeof WebinarRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiPublicSumitReturnRoute: typeof ApiPublicSumitReturnRoute
  ApiPublicSumitWebhookRoute: typeof ApiPublicSumitWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webinar': {
      id: '/webinar'
      path: '/webinar'
      fullPath: '/webinar'
      preLoaderRoute: typeof WebinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sumit-webhook': {
      id: '/api/public/sumit-webhook'
      path: '/api/public/sumit-webhook'
      fullPath: '/api/public/sumit-webhook'
      preLoaderRoute: typeof ApiPublicSumitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sumit-return': {
      id: '/api/public/sumit-return'
      path: '/api/public/sumit-return'
      fullPath: '/api/public/sumit-return'
      preLoaderRoute: typeof ApiPublicSumitReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThankYouRoute: ThankYouRoute,
  WebinarRoute: WebinarRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiPublicSumitReturnRoute: ApiPublicSumitReturnRoute,
  ApiPublicSumitWebhookRoute: ApiPublicSumitWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
